### PR TITLE
Env vars should override the hardcoded configurations

### PR DESCRIPTION
**Pull request by manniniandrea**
Since the ci/cd pipeline should be able to override the hard coded options to better adapt to everyone use case, like having multiple buckets for every deploy environment, I changed the order in which options are evaluated. If you feel like this is a breaking change, I can add another option, which we can call it something like "preferEnvVars", to enable this feature. This PR also includes a fix allowing "awsBucket" option to include sub-directories, which was supported in some old version of the package.

### CODE REVIEW

**Comment by bojanbass** [comment]
Hi. Sorry for my late response. I would like an explanation why ENV vars should take precedence over input options? I suppose if you need to read ENV vars, you set only those?

**Comment by manniniandrea** [comment]
Hello, don’t worry, take your time. To answer your question, we tend to use
nx cache configurations, for the local/dev environment, hard coded in the
nx.json file so the newcomers won’t have to configure anything to quick
start exploring the repo. While on the pipeline, our build engineers need
to overwrite such configurations to properly configure the available
environments depending on which branch is being built. For this reason it
is necessary for us to have such a mechanism so the pipeline, and
consequently the Build Engineer responsible for the project, can override
whatever configuration the developer sets for the local environment,
moreover, this configuration workflow minimizes the risk of  picking up any
test configuration leftovers and gives our build engineers more control
over the environment configuration process.

**Comment by bojanbass** [comment]
I understand your case, but this would be a breaking change for many consumers. `preferEnvVars` idea could solve the problem, however it's not so clean solution. Is there any possible way to do it without introducing breaking changes?

**Comment by bojanbass** [comment]
@manniniandrea, one idea to solve your problem is to store `.env` in the root of your NX workspace where you can set the AWS env variables for local development. The `.env` should be pushed to git. This way you can easily override the values on CI to be more flexible. I'm still hesitant about making ENV variables override the config values, it seems counter-intuitive as it is similar to how arguments or NX executor values override ENV vars.

**Comment by bojanbass** [comment]
After some brainstorming I decided to switch to prefer ENV vars over options as your use case seems to be the most often one in practice. Also, a logic for bucket sub-paths is a great addition. Thank you for your contribution.

**Pull request merged**
