### PR TITLE
feat(nx-aws-cache): foreign machine cache support

### LINKED ISSUE #368: Allow to reuse cache generated on other machines
### Problem
I'm running code on different nodes on CI pipeline execution.
During execution, an attempt of loading the remote cache ends up with the error, as nx does not allow the use of cache from different machines.

Screenshot 2023-08-09 at 14 30 22

### Proposed solution
Extend config with `trustForeignMachineCache?: boolean` property, which will allow to reuse cache generated on machines different than current (by removing `source` file from downloaded `tar`).

### Workarounds
There is a [known workaround](https://nx.dev/recipes/troubleshooting/unknown-local-cache#you-share-cache-with-another-machine-using-a-network-drive) by setting `REJECT_UNKNOWN_LOCAL_CACHE=0` env variable, but this approach is discouraged. It should be the responsibility of `RemoteCache` provider (like `nx-aws`) instead of nx

Please share your POV about this idea. If you have no red flags, let me know and I will prepare a PR for that.

### PR DESCRIPTION
**Pull request by SebastianSedzik**
Screenshot 2023-08-09 at 14 30 22

### Description
~~Add the possibility to use cache generated on different machines.
To enable this option, a new config property was added `trustForeignMachineCache` (or `NXCACHE_TRUST_FOREIGN_MACHINE_CACHE` env variable).
By default option is **disabled**.~~

EDIT: exclude `source` file from remote caching to allow reusing cache generated on different machine.  

This resolves #368

### CODE REVIEW

**Comment by SebastianSedzik** [comment]
Please do not merge, as the problem is probably a regression on the nx side.
Please wait for the final decision [on this issue](https://github.com/nrwl/nx/issues/18642).

**Comment by josokinas** [comment]
Any update on this topic please?

**Comment by FrozenPandaz** [comment]
Hey all :wave:, I'm from the Nx Core team. Just wanted to give my 2 cents here.

No change should have to be made here after https://github.com/nrwl/nx/pull/19059 lands.

As a small note.. The `source` file does not need to be uploaded and downloaded. If there's a way to exclude it, that would be good because there's no need for remote caches to store or retrieve that file. Deleting/unlinking the file is one way of doing it but if there are other ways to exclude uploading and downloading the file, that would be good too.

**Comment by ddivecs** [comment]
> Hey all 👋, I'm from the Nx Core team. Just wanted to give my 2 cents here.
> 
> No change should have to be made here after [nrwl/nx#19059](https://github.com/nrwl/nx/pull/19059) lands.
> 
> As a small note.. The `source` file does not need to be uploaded and downloaded. If there's a way to exclude it, that would be good because there's no need for remote caches to store or retrieve that file. Deleting/unlinking the file is one way of doing it but if there are other ways to exclude uploading and downloading the file, that would be good too.

If thats the case, maybe this PR is still correct (unlink the source file since its not necessary) but just make it the default behavior instead of gated behind a flag?

**Comment by SebastianSedzik** [comment]
@FrozenPandaz thanks for the info!

Just to double check, @FrozenPandaz you are saying that it is fixed on NX side, but also, it is a good practise to removing source file by custom cache providers by their own (even before uploading to save storage space)

Im that case, I totally agree with @ddivecs, to remove flag and mark it as default behavior. (And removing source file even before uploading cache to storage)

**Comment by SebastianSedzik** [comment]
I made some changes in the PR.
Currently source file is excluded during packing and unpacking a tar archive (@FrozenPandaz can you confirm that is something that you suggested? BTW thanks for the info)

**Comment by SebastianSedzik** [comment]
@bojanbass @ddivecs May I ask for a review?

**Comment by bojanbass** [comment]
> @bojanbass @ddivecs May I ask for a review?

How can I test this feature? I'm unfamiliar with when `source` is present, is this Lerna specific? Maybe you could add some comments in the code as to why we need this or reference an issue?

**Comment by ddivecs** [comment]
> > @bojanbass @ddivecs May I ask for a review?
> 
> How can I test this feature? I'm unfamiliar with when `source` is present, is this Lerna specific? Maybe you could add some comments in the code as to why we need this or reference an issue?

Its a file that is added by NX but should not be checked if you are a remote-cache runner implementing the remote-cache interface. the file can be found in the folder of a particular cache hash.

The PR @FrozenPandaz linked to fixes the issue from the NX side by not reading the file in most cases, but it seems there is still issues in some edge cases https://github.com/nrwl/nx/issues/19159. Simply not including the file when creating/extracting the remote cache should avoid the problem.

A code comment might make this clear in the future. Something explaining that nx uses machineID to check integrity, but this conceptually does not work for distributed CI jobs.

**Comment by SebastianSedzik** [comment]
@bojanbass @ddivecs Thanks for the responses! I've added a [explanation comment](https://github.com/bojanbass/nx-aws/pull/376/files#diff-5a00cd6680cd9f53b82eb2605a917020e6b2fbb6a74546e00cceb571474cd446R259-R263). Please let me know if this is enough or I should put more context there.

> How can I test this feature?

There are two things to check:
1. Run one of the `cacheableOperations` on two different machines. Before my changes, execution on 2nd machine (returning operation from remote cache) should (unfortunately just sometimes :(, probably when artifact was generated on different NX version that is currently used in project) end up with the following error "The local cache artifact in x was not been generated on this machine.". After my change, the error should not appear. 
2. Generated artifacts should not contain `source` file

> I'm unfamiliar with when source is present, is this Lerna specific?

No, it is not Lerna specific, in [this](https://github.com/nrwl/nx/issues/19159) and [this](https://github.com/nrwl/nx/issues/18642) issue, reporters that do not use Lerna are experiencing the same problem.

**Comment by bojanbass** [comment]
@SebastianSedzik, awesome work. Even if I can't find `source` in any of my cache folders, I believe it is the right thing to support from all the comments. Merging.

**Pull request merged**
