### PR TITLE
Use consistent semver for all @aws-sdk/* dependencies

### PR DESCRIPTION
**Pull request by terrymun**
This PR ensures that the `@aws-sdk/*` dependencies listed in `package.json` have consistent semver, to avoid running into issues in the future with unmet peer dependency versions, e.g.:

Screenshot 2024-05-08 at 11 46 02

### CODE REVIEW

**Comment by terrymun** [comment]
Hi @bojanbass, would you mind having a look at this PR? I’m more than happy to help update it if any changes are needed.

**Comment by bojanbass** [comment]
Hi @terrymun, thank you for the PR. I was thinking about this and looks like dependabot is not configured ideally. I've changed the config so that it groups all `aws-sdk` packages in the same PR. Still, the versions are not aligned, but only a single PR is created. Take a look at this example please: https://github.com/bojanbass/nx-aws/pull/611
All packages take the latest version. Is this good enough? I would just like to make this automated if possible.

**Comment by terrymun** [comment]
@bojanbass #611 looks good but it seems one of the AWS SDK dependency isn’t pinned. Is that intentional?

If you want to automate dependency upgrades I can recommend the Renovate bot, it’s pretty straightforward to use and I’m happy help set it up if needed.

**Comment by bojanbass** [comment]
Which one is not pinned?

**Comment by terrymun** [comment]
Closing as it is superseded by #611

**Pull request closed without merging**
